### ISSUE TITLE
Don't know dataset format

### ISSUE THREAD

**Issue by collin0825** [lasigeBioTM/K-RET#1]
thank you for provide this code, but I don't know what the data format, can you provide the dataset directlty, and I don't know how to split data, the dataset url you provide I don't which to use like DDI

**Comment by dpavot** [comment]
I appreciate your interest in K-RET. 
Regarding your question about the data format, the dataset provided follows the standard format for Bert-based training. Here you can find the split [https://github.com/lasigeBioTM/K-RET/tree/main/datasets/pgr_corpus](https://github.com/lasigeBioTM/K-RET/tree/main/datasets/pgr_corpus) for the PGR dataset. I didn't openly make the DDI split available because it is not my dataset. 
As for splitting the data, our approach was to split the data into training, validation, and test sets, with a ratio of 60%, 10%, and 30%, respectively. However, you can adjust these ratios to meet your specific needs.
I hope this information is helpful to you. Please don't hesitate to reach out with any further questions or concerns here or vi e-mail.
